# Configurations for arguments in arg_list.go:
account_id = "0"
alt_hosts = ""
background = "true"
block_size = "65536"
cluster = "default"
compress = "false"
config-file = "bytehouse_conf.toml"
connection_open_strategy = "random"
connection_timeout = "3"
consul_http_host = "10.231.255.195"
consul_http_port = "2280"
database = "default"
debug = "false"
host = "localhost"
ignore_syntax = "false"
no_delay = "true"
password = ""
pool_size = "0"
port = "9000"
pprof = "false"
psm = ""
query = ""
quota_key = ""
read_timeout = "0"
secure = "false"
skip_verification = "false"
target_account = "0"
target_role = ""
target_user = "0"
tls_config = ""
token = ""
user_id = "0"
username = "default"
write_timeout = "0"

# Configurations for query settings:
TEST_KNOB = 0
active_role = "*"
add_http_cors_header = false
additional_background_pool_size = 8
aggregation_memory_efficient_merge_threads = 0
aggressive_merge_in_optimize = true
allow_ddl = true
allow_distributed_ddl = true
allow_experimental_cross_to_join_conversion = true
allow_experimental_data_skipping_indices = false
allow_experimental_map_type = false
allow_experimental_multiple_joins_emulation = true
allow_hyperscan = true
allow_introspection_functions = false
allow_map_access_without_key = true
allow_simdjson = true
ansi_sql = false
asterisk_left_columns_only = false
background_consume_schedule_pool_size = 16
background_dump_thread_pool_size = 16
background_pool_size = 16
background_schedule_pool_size = 16
batch_size_in_attaching_parts = 1024
calculate_text_stack_trace = true
cancel_http_readonly_queries_on_client_close = false
cascading_refresh_materialized_view = true
catalog_enable_streaming_rpc = true
check_consistency = true
check_query_single_value_result = false
cnch_alter_task_timeout = 200
compile = false
compile_expressions = false
connect_timeout = 10
connect_timeout_with_failover_ms = 50
connection_check_pool_size = 16
connections_with_failover_max_tries = 3
conservative_merge_predicate = true
constraint_skip_violate = false
count_distinct_implementation = "uniqExact"
databases_load_pool_size = 3
debug_cnch_force_commit_parts_rpc = false
debug_cnch_remain_temp_part = false
decimal_check_overflow = true
decrease_error_period = 600
deduce_part_eliminate = true
disable_perfect_shard_auto_merge = false
disable_remote_stream_log = false
distributed_aggregation_memory_efficient = false
distributed_connections_pool_size = 1024
distributed_ddl_task_timeout = 180
distributed_directory_monitor_batch_inserts = false
distributed_directory_monitor_sleep_time_ms = 100
distributed_group_by_no_merge = false
distributed_perfect_shard = false
distributed_to_local = false
empty_result_for_aggregation_by_empty_set = false
enable_ab_index_optimization = false
enable_async_build_bitmap_in_attach = false
enable_bloom_filter = false
enable_debug_queries = true
enable_detail_event_log = false
enable_deterministic_sample_by_range = false
enable_dictionary_compression = false
enable_distributed_stages = false
enable_final_for_delta = true
enable_final_sample = false
enable_http_compression = false
enable_merge_scheduler = false
enable_operator_level_profile = false
enable_optimize_predicate_expression = false
enable_query_cache = false
enable_query_level_profiling = false
enable_query_metadata = false
enable_range_bloom_filter = false
enable_sample_by_range = false
enable_sync_build_bitmap = false
enable_sync_fetch = false
enable_sync_from_ha = false
enable_testlog_to_console = false
enable_unaligned_array_join = false
enable_variadic_arraySetCheck = true
enable_view_based_query_rewrite = false
encrypt_key = ""
expired_end_hour_to_merge = 12
expired_start_hour_to_merge = 12
external_table_functions_use_nulls = true
extremes = false
fallback_to_stale_replicas_for_distributed_queries = true
force_index_by_date = false
force_primary_key = false
force_release_when_mmap_exceed = false
format_csv_allow_double_quotes = true
format_csv_allow_single_quotes = true
format_csv_write_utf8_with_bom = false
format_protobuf_default_length_parser = false
format_protobuf_enable_multiple_message = true
format_schema = ""
free_resource_early_in_write = false
fsync_metadata = true
funnel_old_rule = false
group_by_overflow_mode = ""
group_by_two_level_threshold = 100000
group_by_two_level_threshold_bytes = 100000000
http_connection_timeout = 1
http_headers_progress_interval_ms = 100
http_max_multipart_form_data_size = 1073741824
http_native_compression_disable_checksumming_on_decompress = false
http_receive_timeout = 1800
http_send_timeout = 1800
http_zlib_compression_level = 3
idle_connection_timeout = 3600
input_format_allow_errors_num = 0
input_format_allow_errors_ratio = 0.0
input_format_defaults_for_omitted_fields = false
input_format_import_nested_json = false
input_format_json_aggregate_function_type_base64_encode = false
input_format_max_map_key_long = 80
input_format_parse_null_map_as_empty = true
input_format_skip_null_map_value = true
input_format_skip_unknown_fields = false
input_format_values_interpret_expressions = true
insert_allow_materialized_columns = false
insert_deduplicate = true
insert_distributed_sync = false
insert_distributed_timeout = 0
insert_quorum = 0
insert_quorum_timeout = 600000
interactive_delay = 100000
join_any_take_last_row = false
join_use_nulls = false
joined_subquery_requires_alias = false
kafka_max_partition_fetch_bytes = 1048576
kafka_session_timeout_ms = 180000
kms_token = ""
load_balancing_offset = 0
local_disk_cache_thread_pool_size = 16
log_id = ""
log_profile_events = true
log_queries = false
log_queries_cut_to_length = 100000
log_query_settings = true
log_query_threads = true
low_cardinality_allow_in_native_format = true
low_cardinality_max_dictionary_size = 8192
low_cardinality_use_single_dictionary_for_part = false
mark_cache_min_lifetime = 10000
max_ast_depth = 1000
max_ast_elements = 50000
max_block_size = 65536
max_bytes_before_external_group_by = 0
max_bytes_before_external_sort = 0
max_bytes_before_remerge_sort = 1000000000
max_bytes_in_distinct = 0
max_bytes_in_join = 0
max_bytes_in_set = 0
max_bytes_to_read = 0
max_bytes_to_sort = 0
max_bytes_to_transfer = 0
max_columns_to_read = 0
max_compress_block_size = 1048576
max_compressed_bytes_to_read = 0
max_concurrent_queries_for_user = 0
max_distributed_connections = 1024
max_execution_speed = 0
max_execution_speed_bytes = 0
max_execution_time = 0
max_expanded_ast_elements = 50000
max_fetch_partition_retries_count = 5
max_hdfs_read_network_bandwidth = 0
max_hdfs_write_buffer_size = 1048576
max_ingest_columns_size = 10
max_ingest_rows_size = 50000000
max_insert_block_size = 1048576
max_insert_block_size_bytes = 0
max_memory_usage = 0
max_memory_usage_for_all_queries = 0
max_memory_usage_for_user = 0
max_network_bandwidth = 0
max_network_bandwidth_for_all_users = 0
max_network_bandwidth_for_fetch = 0
max_network_bandwidth_for_user = 0
max_network_bytes = 0
max_parallel_replicas = 1
max_parallel_threads_for_resharding = 32
max_partitions_for_resharding = 4
max_partitions_per_insert_block = 100
max_parts_to_optimize = 1000
max_pipeline_depth = 1000
max_query_size = 262144
max_read_buffer_size = 1048576
max_replica_delay_for_distributed_queries = 120
max_replica_delay_for_write_queries = 0
max_result_bytes = 0
max_result_rows = 0
max_rows_for_resharding = 10000000000
max_rows_in_distinct = 0
max_rows_in_join = 0
max_rows_in_set = 0
max_rows_to_group_by = 0
max_rows_to_read = 0
max_rows_to_schedule_merge = 500000000
max_rows_to_sort = 0
max_rows_to_transfer = 0
max_rpc_read_timeout_ms = 10000
max_sample_size_for_optimize = 1000000
max_streams_to_max_threads_ratio = 1.0
max_subquery_depth = 100
max_temporary_columns = 0
max_temporary_non_const_columns = 0
max_threads = 0
max_uncompressed_bytes_to_read = 0
memory_tracker_fault_probability = 0.0
merge_tree_coarse_index_granularity = 0
merge_tree_max_rows_to_use_cache = 1048576
merge_tree_min_rows_for_concurrent_read = 163840
merge_tree_min_rows_for_seek = 0
merge_tree_uniform_read_distribution = true
mimic_replica_name = ""
min_bytes_to_use_direct_io = 0
min_compress_block_size = 65536
min_count_to_compile = 3
min_count_to_compile_expression = 3
min_execution_speed = 0
min_execution_speed_bytes = 0
min_insert_block_size_bytes = 268435456
min_insert_block_size_rows = 1048576
mysql_max_rows_to_insert = 65536
network_compression_method = "LZ4"
network_zstd_compression_level = 1
ntimes_slower_to_alarm = 3
odbc_max_field_size = 1024
optimize_map_column_serialization = false
optimize_min_equality_disjunction_chain_length = 3
optimize_move_to_prewhere = true
optimize_skip_unused_shards = false
optimize_subpart_key = -1
optimize_subpart_number = -1
optimize_throw_if_noop = false
output_format_json_escape_forward_slashes = true
output_format_json_quote_64bit_integers = false
output_format_json_quote_denormals = false
output_format_parquet_row_group_size = 1000000
output_format_pretty_color = true
output_format_pretty_max_column_pad_width = 250
output_format_pretty_max_rows = 10000
output_format_write_statistics = true
parallel_fetch_part = 1
parallel_replica_offset = 0
parallel_replicas_count = 0
parallel_view_processing = false
part_cache_min_lifetime = 3600
parts_load_pool_size = 48
parts_preallocate_pool_size = 16
pathgraph_threshold_x = 0
pathgraph_threshold_y = 0
poll_interval = 10
prefer_localhost_replica = true
preferred_block_size_bytes = 1000000
preferred_max_column_in_block_size_bytes = 0
preload_checksums_and_primary_index_cache = false
priority = 0
process_list_block_time = 30000
query_auto_retry = false
query_auto_retry_millisecond = 300000
query_cache_min_lifetime = 1000
query_worker_fault_tolerance = false
queue_max_wait_ms = 5000
read_backoff_max_throughput = 1048576
read_backoff_min_events = 2
read_backoff_min_interval_between_events_ms = 1000
read_backoff_min_latency_ms = 1000
read_overflow_mode = ""
readonly = 0
receive_timeout = 300
remote_query_memory_table = false
replace_running_query = false
replication_alter_columns_timeout = 16
replication_alter_partitions_sync = 1
restore_table_expression_in_distributed = true
rm_zknodes_while_alter_engine = false
select_sequential_consistency = 0
send_logs_level = "fatal"
send_progress_in_http_headers = false
send_timeout = 300
show_table_uuid_in_table_create_query_if_not_nil = true
skip_history = false
skip_nullinput_notnull_col = false
skip_unavailable_shards = false
slow_query_ms = 0
snappy_format_blocked = false
stream_flush_interval_ms = 7500
stream_poll_timeout_ms = 500
strict_rows_to_schedule_merge = 50000000
table_function_remote_max_addresses = 1000
tables_load_pool_size = 8
tcp_keep_alive_timeout = 0
tealimit_order_keep = false
timeout_before_checking_execution_speed = 0
totals_auto_threshold = 0.0
totals_mode = ""
use_client_time_zone = false
use_index_for_in_with_subqueries = true
use_uncompressed_cache = true
virtual_warehouse = ""
virtual_warehouse_write = ""
